server:
  url: http://localhost:8080/geoserver
  verifytls: false

credentials:
  user: admin
  pass: geoserver

db:
  pg_host:
    local: localhost
    docker: geodatabase
  pg_port:
    local: 6432
    docker: 5432
  pg_db: acceptance
  pg_user: geoserver
  pg_password: geoserver
  pg_schema: public
